### ISSUE TITLE
Design Docs Review #1

### ISSUE THREAD

**Issue by gorterd** [allsouza/WhateverNote#1]
Your docs are looking great, Andre, and I love the name! Here's my feedback so far (checkmarks are next to things you should do, other suggestions / comments are just bullets). Let me know if you have any questions!

**MVP LIST**
- [x] Notes
  - [x] Second bullet point: what can users do with selected notes? I’d make just seeing the list of all notes a separate bullet point as well
  - [x] Users should also be able to delete notes
  - Consider adding that users can see preview of notes in list
- [x] Notebooks
  - [x] Add that users can update name of and delete notebooks
  - [x] Add how users will see notebooks (index page?), as well as the list of notes within a notebook
  - [x] Make a separate bullet point about users adding / removing / moving notes from and to a notebook 
- [x] Tags
  - [x] Add that users can delete tags

**SCHEMA**
- [x] Be explicit about which columns have indices (not just note at bottom about index on all foreign keys), and consider adding indices to non foreign key columns that will be used for lookup frequently (eg email)
- [x] Rename your notebook / notes joins table (now it’s called notebook users)
- Consider using foreign key to notebook in notes table instead of having a joins table (since it appears to me like one note can’t belong to multiple notebooks)

**Comment by allsouza** [comment]
All issues addressed.
Notebook/Notes joins table removed, notes now have a notebook_id 
Thanks!

**Comment by gorterd** [comment]
Your revisions look great!
