### ISSUE TITLE
DD #2 Sample State, Backend Routes

### ISSUE THREAD

**Issue by gorterd** [allsouza/WhateverNote#2]
**Sample State**
- [x] Notes  and notebooks appear to be ordered chronologically by when they were last edited, and to display a corresponding time since last edited / date of last edit; I'd include a property holding this data in both of their respective slices of state
- It might be easier to change your `ui.modal` property so that it points to a string; the idea being that you'll never have two modals up at once, and so having several booleans would require you to probably do some validations to make sure at most one is true at a time
- Honestly, the rest of your sample state looks excellent; not much more in the way of feedback

**Backend Routes**
- I'd suggest nesting your notes POST route under notebooks, so that you can easily pass along the id of the notebook it should be contained within
- I'd suggest you create a custom route for adding tags to notes. The user enters a string, which would create a new tag if it doesn't exist already, and regardless would add a record to the joins table. This could all be done on the backend, and probably warrants its own route.
- I'd also suggest making a route for removing a tag from a note, because that involves removing an entry in the corresponding joins table

**Comment by gorterd** [comment]
Noticed a couple typos in my feedback and revised it!

**Comment by allsouza** [comment]
Thanks for the great feedback. I'll revise it tomorrow.

**Comment by allsouza** [comment]
I tried also making the changes from the suggestions.  Will get some more clarification at our 1:1
