### ISSUE TITLE
DD #3 Frontend Routes & Components

### ISSUE THREAD

**Issue by gorterd** [allsouza/WhateverNote#3]
**Suggested Changes**
- [x] It appears the `NavBar` only appears on the splash page, and not in the primary webapp or auth pages. I'd suggest nesting that under the route for the splash page.
- [x] On the other hand, it appears the sidebar appears on every page of the primary webapp. You might consider nesting all your primary webapp routes (ie all but splash and auth routes) under some parent route (e.g. `/parent/notes`), so that all of them render the sidebar. In any case, however you choose to structure it, you'll want a component (possibly with child components) for the SideBar
- [x] the components for `/notes` and `/notes/:id` are the same, no need for different routes there.  Similarly for the notes index / notes edit that are nested are notebooks and tags. I see the reasoning for keeping the all notes, notebook notes, and tag notes routes separate so that you can make use of the wildcard in the path, but probably don't need different routes for index and edit for each. There's no page that just renders the notes index or just the notes edit
- [x] you'll want components for the tags index; while it doesn't warrant its own route because its a drawer that comes out of the sidebar, it should be a component. Since that drawer is always accessible from the sidebar, you'd probably not want to make that component routed.
- [x] you'll need create and edit components for notebooks and tags (they're all modals); could be less than 4 components since some of them are similar enough that you could make them reusable

**Other Notes / Ideas**
- the signup and login forms look almost identical; could probably reuse a component there
- some of your components could be broken down further, up to you. e.g., you could extract out header components for notes edit & index, and notebooks index, etc

Let me know if you have questions about this or any of the other feedback I provided on your docs! As always, it's up to you whether you want to make any of the changes I suggest.

**Comment by allsouza** [comment]
Made the appropriate changes to my frontend routes.  Will want to talk some more during our 1:1 about the last suggestion to break down components further
