### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by gorterd** [allsouza/WhateverNote#4]
Looks fantastic Andre, nice work!

Some recommended changes
- Splash
  - [x] While taking some design liberties is fine (e.g. changing color scheme), you'll probably want your layout to look similar to the real thing, so it's very easy for someone to compare the two and notice how well you've cloned things. As a result, I'd swap sides for the graphic and the text in the first section of the splash page to match Evernote
  - [x] Some fonts on splash are too different (size, weight, spacing, and capitalization): the subheader in the first splash pane ('WhateverNote is here to help...'); all the text for second pane ('How It Works'); text in footer
  - [x] add transition to the button hover effect for 'Sign up for free' (so that the color change fades in/out), as well as any other buttons with same hover effect
  - [x] copyright in footer should be left-aligned

- Session Forms
  - [x] background image should fill full page (it cuts off for me 3/4 of the way down), and I would choose a different image that doesn't have a watermark (added resource to Trello for getting free images)
  - [x] the 'Log in' after 'Already have an account?' should be smaller
  - [x] sign up / Log in buttons don't work for me when they fail validation; validation errors should be displayed as errors in the form in the same way they're rendered on Evernote
  - [x] Login should start with just an input for email address, clicking continue should then check if that email address already exists, if not, render error message, if so, show password input (replicate Evernote login form)

**Comment by allsouza** [comment]
Evernote just checks that something is in the email field and allows continue to be clicked.  Replicated that behaviour

**Comment by gorterd** [comment]
Oops, sorry about the misinformation. Excellent work!
