### ISSUE TITLE
Notebooks

### ISSUE THREAD

**Issue by gorterd** [allsouza/WhateverNote#6]
Just as with the last MVP, very excellent, polished work, Andre! Here's my feedback:

**Functionality**
- [x] The name of the notebook in the upper left of the active note should be a link to that particular notebook.

**Styling**
- [x] When I'm within a particular notebook, it should be highlighted in the sidebar, and `All Notes` / `Notebooks` should lose their highlighting.
- [x] When I'm in one notebook, and I move an active note to another notebook, the moved note should disappear from the index on the left, and another note should become active. (Alternatively, I think it would make sense as a design choice to keep the moved note active but go to its new notebook -- however, that doesn't seem to be the way Evernote does it).
- [x] In the notebooks index, collapsing / expanding a notebook should not change the widths of the columns in the table

**Comment by allsouza** [comment]
For the second styling issue, I agree more with your suggestion and am making that design choice.  I don't agree with how Evernote does their notebook change.  If not ok just let me know.

**Comment by gorterd** [comment]
Yeah, that's fine. Really nice work with the styling changes!

One small heads up (but don't worry about implementing now) -- when you're in a notebook and move a note to another notebook, the note loses its focus (border) in the notes index on the left.
